# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f5197ecad55e50fdc0bd5f5d6d518814c8a6192c2310f39879e10a0d288f5078c2339bf36b1164d266906b17688fd5dd66a555380d9e035fdd44d969028d03d

test:
  secret_key_base: 96b24370d83eea34a0069dab4636d9fa2f9de84548e6f497fe87b22e3776add493df87efeada44ceb7c8845c3375fc6d93fdc11e81b64d9fb6d8dec18de7e2c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
